"""Regenerate docs_cpu/API_REFERENCE*.md from the CLI's own tables.

The tables live in the top-level bitsandbytes_cpu_cli.py and are rendered two ways: plain
text for `bitsandbytes-cpu help`, markdown for these files. Generating them from one
source is what keeps the terminal output and the document from drifting apart.

Run from the repository root:
    python tools/gen_api_reference.py
"""
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
sys.path.insert(0, ROOT)

BACKTICK = chr(96)


def main():
    from bitsandbytes_cpu_cli import render_markdown

    md = render_markdown()
    note_zh = (f"<!-- 本文件由 {BACKTICK}bitsandbytes-cpu help --markdown{BACKTICK} "
               f"生成,请勿手改;要改内容请改 bitsandbytes_cpu_cli.py。 -->")
    note_en = (f"<!-- Generated by {BACKTICK}bitsandbytes-cpu help --markdown{BACKTICK}; "
               f"do not edit by hand. Edit bitsandbytes_cpu_cli.py instead. -->")

    zh = os.path.join(ROOT, "docs_cpu", "API_REFERENCE.md")
    en = os.path.join(ROOT, "docs_cpu", "API_REFERENCE_EN.md")
    with open(zh, "w", encoding="utf-8", newline="\n") as fh:
        fh.write(note_zh + "\n" + note_en + "\n\n" + md)
    with open(en, "w", encoding="utf-8", newline="\n") as fh:
        fh.write(note_en + "\n\n" + md)

    for p in (zh, en):
        n = len(open(p, encoding="utf-8").read().splitlines())
        print(f"  wrote {os.path.relpath(p, ROOT)}  ({n} lines)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
